### ISSUE TITLE
Error while onboarding a new project

### ISSUE THREAD

**Issue by pdhoolia** [pdhoolia/se-agent#7]
I see the following on console:

```
2024-11-07 22:47:06,660 - se-agent - DEBUG - Projects store: /Users/pdhoolia/projects-store
Added project 'pdhoolia/se-agent-test-repo' to projects list.
2024-11-07 22:47:06,665 - se-agent - ERROR - Error during project onboarding.
Traceback (most recent call last):
  File "/Users/pdhoolia/fun/se-agent/se_agent/listener_core.py", line 48, in onboard_project
    project.onboard()
  File "/Users/pdhoolia/fun/se-agent/se_agent/project.py", line 240, in onboard
    self.clone_repository()
  File "/Users/pdhoolia/fun/se-agent/se_agent/project.py", line 79, in clone_repository
    if os.listdir(self.repo_folder):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/pdhoolia/projects-store/pdhoolia/se-agent-test-repo/repo'
```

**Comment by se-agent** [comment]
The error you're encountering is a `FileNotFoundError` which occurs because the `self.repo_folder` directory does not exist at the time you are trying to list its contents in the `clone_repository` method. This happens because the directory is expected to be created before checking its contents.

To fix this issue, you should ensure that the `self.repo_folder` directory exists before attempting to list its contents. Here is a suggested change to the `clone_repository` method in `se_agent/project.py`:

```python
def clone_repository(self):
    """ Clone the repository if it doesn't exist """
    # Ensure the repository folder exists
    os.makedirs(self.repo_folder, exist_ok=True)
    
    # Check if the repository is already cloned
    if os.listdir(self.repo_folder):
        logger.info("Repository already cloned.")
        git_cmd = git.cmd.Git()
        try:
            safe_directories = git_cmd.config('--global', '--get-all', 'safe.directory').splitlines()
        except git.GitCommandError:
            # If the command fails, assume no safe directories are set
            safe_directories = []
        # Add to safe directories if not already present
        if self.repo_folder not in safe_directories:
            git_cmd.config('--global', '--add', 'safe.directory', self.repo_folder)
            logger.info(f"Safe directory added: {self.repo_folder}")
        return

    # Clone the repository
    logger.info(f"Cloning repository '{self.info.repo_full_name}'...")
    
    try:
        repo = self.github.get_repo(self.info.repo_full_name)

        # Prepare the local repository folder
        logger.info(f"Using local repository folder: '{self.repo_folder}'")

        # Clone the repository
        logger.info(f"Cloning repository into '{self.repo_folder}'...")
        clone_url = repo.clone_url.replace('https://', f'https://{self.github_token}@')
        try:
            git.Repo.clone_from(clone_url, self.repo_folder)
            logger.info(f"Repository cloned successfully into '{self.repo_folder}'")
            git.cmd.Git().config('--global', '--add', 'safe.directory', self.repo_folder)
            logger.info(f"Safe directory added: {self.repo_folder}")
        except Exception as e:
            logger.error(f"Error cloning repository: {e}")
            raise
    except Exception as e:
        logger.error(f"Error accessing repository: {e}")
        raise
```

### Explanation:
- The change involves adding `os.makedirs(self.repo_folder, exist_ok=True)` at the start of the `clone_repository` method. This ensures that the directory is created if it does not exist, preventing the `FileNotFoundError`.
- The rest of the logic remains the same, and the method will continue to check if the repository is already cloned and proceed with cloning if necessary.

**Comment by pdhoolia** [comment]
can you please point out the changes proposed in a git diff format?

**Comment by se-agent** [comment]
Certainly! Here's the change presented in a `git diff` format:

```diff
diff --git a/se_agent/project.py b/se_agent/project.py
index 1234567..89abcde 100644
--- a/se_agent/project.py
+++ b/se_agent/project.py
@@ -76,6 +76,9 @@ def clone_repository(self):
     """ Clone the repository if it doesn't exist """
     # Check if the repository is already cloned
     
+    # Ensure the repository folder exists
+    os.makedirs(self.repo_folder, exist_ok=True)
+
     if os.listdir(self.repo_folder):
         logger.info("Repository already cloned.")
         git_cmd = git.cmd.Git()
``` 

### Explanation of the Diff:
- **Line Addition**: The line `os.makedirs(self.repo_folder, exist_ok=True)` is inserted before checking the contents of `self.repo_folder`. This ensures the directory exists, thus avoiding the `FileNotFoundError`.
